### PR TITLE
Improved slide styling options and added some features

### PR DESCRIPTION
**Pull request by nelsonkam**
Added `title` and `description` styling support for `pageArray` similar to `imgStyle` for images. Title and description are now centered (text alignment) by default. Added backwards compatible support for static image assets for `pageArray`.
Resolves: #5

### CODE REVIEW

**Comment by FuYaoDe** [comment]
Thanks for your enthusiastic pull requests
But I think https://github.com/FuYaoDe/react-native-app-intro/pull/34 this solution better
What do you think?

**Comment by nelsonkam** [comment]
@FuYaoDe I totally agree with this but would you mind adding center alignment for title and description + title/description styling ?

**Comment by FuYaoDe** [comment]
title add center is ok but description not good, because maybe someone described very long will look unbalanced, and pageArray add title/description styling is good feature

**Comment by nelsonkam** [comment]
I understand, you are right. Thanks for your attention and this helpful library.

Cheers !

**Pull request closed without merging**
