### PR TITLE
Update the Android status bar to match the background color

### PR DESCRIPTION
**Pull request by SandroMachado**
This PR adds support to update the status bar to match the slide background color in Android. This is only available for basic usage.

sample-android

```
  render() {
    const pageArray = [{
      title: 'Page 1',
      description: 'Description 1',
      img: 'https://goo.gl/Bnc3XP',
      imgStyle: {
        height: 80 * 2.5,
        width: 109 * 2.5,
      },
      backgroundColor: '#fa931d',
      fontColor: '#fff',
      level: 10,
    }, {
      title: 'Page 2',
      description: 'Description 2',
      img: 'https://goo.gl/Bnc3XP',
      imgStyle: {
        height: 93 * 2.5,
        width: 103 * 2.5,
      },
      backgroundColor: '#a4b602',
      fontColor: '#fff',
      level: 10,
    }];
    return (
      <AppIntro
        onNextBtnClick={this.nextBtnHandle}
        onDoneBtnClick={this.doneBtnHandle}
        onSkipBtnClick={this.onSkipBtnHandle}
        onSlideChange={this.onSlideChangeHandle}
        pageArray={pageArray}
      />
    );
  }
```

### CODE REVIEW

**Comment by FuYaoDe** [comment]
Thanks!!
But I found your background color is written dead, and in pageArray you can custom `backgroundColor`, maybe this part can be dynamic.
Then the Example section thank you for helping me upgrade, but the scope of change too much, I can't verify whether it's a PR issue or React Native, please don't move the Example section, that's my only job 😄

**Comment by FuYaoDe** [comment]
Oh sorry.... I saw `this.props.pageArray[0].backgroundColor`

**Comment by SandroMachado** [comment]
Thanks for the reply.

The changes in the example section are to update the project to the latest react native version. If you prefer I can move this to another PR. It is easy for the community to test the sample app in the latest version. WDYT?

**Comment by FuYaoDe** [comment]
OK, open a new one PR, I will review too thanks!!

**Comment by SandroMachado** [comment]
@FuYaoDe thanks! I created #43 to update the React Native version for the demo app.

**Comment by FuYaoDe** [comment]
Awesome !!  Looks more harmonious
If I have time I'll add it fade animation to change color
Hopefully there will be no performance issues...

**Comment by SandroMachado** [comment]
@FuYaoDe Thanks :)

**Comment by SandroMachado** [comment]
@FuYaoDe Do you have plans for making a release?

**Comment by FuYaoDe** [comment]
In fact, this is my first project so many stars, I have not tried release let me look at the study :sweat_smile:

**Comment by SandroMachado** [comment]
Great! Please let me know if you need any help. Making releases will help to control the code and breaking changes.

**Pull request merged**
